experiment: fllstm
dataset_name: azure
dataset: 'datasets/microsoft/'
lookbacks: 
  - 2
  - 6
  - 12
  - 24
  - 48
num_epochs: 50
num_rounds: 20
learning_rate: 0.001
input_size: 3
hidden_size: 128 # 50
num_layers: 2 # 1
num_classes: 3
batch_size: 
  - 256
num_clients: 6
fraction_fit: 1 # Sample N% of available clients for training
fraction_evaluate: 1 # Sample N% of available clients for evaluation
min_fit_clients: 6 # Never sample less than N clients for training
min_evaluate_clients: 6 # Never sample less than N clients for evaluation
min_available_clients: 6 # Wait until all N clients are available