experiment: fllstm
dataset_name: azure
dataset: 'datasets/microsoft/'
lookbacks: 
  - 2
  # - 6
  # - 12
  # - 24
  # - 48
  # - 96
num_epochs: 10
num_rounds: 10
learning_rate: 0.001
input_size: 3
hidden_size: 50
num_layers: 1
num_classes: 3
batch_size: 
  # - 16
  # - 32
  - 256